config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
  end
  namespace :admin do
    get 'homes/top'
  end
  # Public routes
  root 'public/homes#top', as: 'top'
  get '/about', to: 'public/homes#about', as: 'about'
  



  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  namespace :public do
    resource :customer, only: [:show, :edit, :update,] do
      get 'my_page', to: 'customers#show'
      get 'information/edit', to: 'customers#edit'
      patch 'information', to: 'customers#update'
      get 'unsubscribe', to: 'customers#unsubscribe'
      patch 'withdraw', to: 'customers#withdraw'
    end
    
    resources :items, only: [:index, :show]


    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete 'destroy_all', on: :collection
    end

    resources :orders, only: [:new, :create, :index, :show] do
      post 'confirm', on: :collection
      get 'thanks', on: :collection # ここで'public/orders/thanks'のルートを定義
    end

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index]
    get '/customer/:id/orders' => 'customers#orders', as: :order_admin_customer
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :customer_id, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    "#{last_name} #{first_name}"
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders, dependent: :destroy

         
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details
  has_one_attached :image
  belongs_to :genre # ジャンルは必須
  has_many :cart_items
  validates :genre, presence: true # バリデーションを追加（ジャンルが必須であることを明示）
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, bank_transfer: 1 }


  enum is_order: { waiting_for_payment: 0, payment_confirmed: 1, in_production: 2, shipping_preparation: 3, shipped: 4 }

  # カート内商品の合計金額を計算
  def calculate_total_amount(cart_items)
    self.total_amount = cart_items.sum do |cart_item|
      cart_item.item.price * cart_item.amount
    end
  end

  # 送料を設定する（例: 一律800円）
  def set_postage
    self.postage = 800
  end


  validates :address, :post_code, :name, :total_amount, :postage, :payment_method, presence: true
  validates :is_order, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum is_production: { not_started: 0, waiting_for_start: 1, in_production: 2, completed: 3 }


  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :is_production, presence: true

  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.all
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end
  
  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end
  
  def orders
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.order(created_at: :desc).page(params[:page]).per(10)  # 1ページ10件表示
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :address, :telephone_number, :post_code, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params) # フォームから受け取ったデータでGenreを作成
    if @genre.save
      redirect_to admin_genres_path, notice: 'ジャンルを作成しました。' # 成功時
    else
      @genres = Genre.all # エラー時に一覧を再取得
      flash.now[:alert] = 'ジャンルの作成に失敗しました。'
      render :index # エラー時に一覧ページを再表示
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: 'ジャンルを更新しました。'
    else
      flash.now[:alert] = 'ジャンルの更新に失敗しました。'
      render :edit
    end
  end


  def genre_params
    params.require(:genre).permit(:name) # 必要なパラメータを許可
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @item = Item.new(is_active: true)
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品を登録しました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: '商品情報を更新しました。'
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :introduction, :is_active, :genre_id, :image)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details.includes(:item)
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:is_order] == "payment_confirmed"
      @order.order_details.update(is_production:"waiting_for_start")
    end
    flash[:notice] = "更新されました。"
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
  params.require(:order).permit(:customer_id, :is_order)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # app/controllers/admin/application_controller.rb
  before_action :authenticate_admin!, if: :admin_url   # ログインを必須にする

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admin/customers/edit.html.erb
<h3 class="mb-4"><%= @customer.last_name + " " + @customer.first_name + "さんの会員情報編集" %></h3>

<%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch, class: "needs-validation" do |f| %>
  <div class="container">
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label">会員ID</label>
      <div class="col-sm-9">
        <p class="form-control-plaintext"><%= @customer.id %></p>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :last_name, "氏名" %></label>
      <div class="col-sm-4">
        <%= f.text_field :last_name, id: "customer_last_name", class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <%= f.text_field :first_name, id: "customer_first_name", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :kana_last_name, "フリガナ" %></label>
      <div class="col-sm-4">
        <%= f.text_field :kana_last_name, id: "customer_kana_last_name", class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <%= f.text_field :kana_first_name, id: "customer_kana_first_name", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :post_code, "郵便番号" %></label>
      <div class="col-sm-9">
        <%= f.text_field :post_code, id: "customer_post_code", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :address, "住所" %></label>
      <div class="col-sm-9">
        <%= f.text_field :address, id: "customer_address", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :telephone_number, "電話番号" %></label>
      <div class="col-sm-9">
        <%= f.text_field :telephone_number, id: "customer_telephone_number", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :email, "メールアドレス" %></label>
      <div class="col-sm-9">
        <%= f.text_field :email, id: "customer_email", class: "form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-3 col-form-label"><%= f.label :is_active, "会員ステータス" %></label>
      <div class="col-sm-9">
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, true, id: "customer_is_active_true", class: "form-check-input" %>
          <%= f.label :is_active, "有効", for: "customer_is_active_true", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, false, id: "customer_is_active_false", class: "form-check-input" %>
          <%= f.label :is_active, "退会", for: "customer_is_active_false", class: "form-check-label" %>
        </div>
      </div>
    </div>
    <div class="text-center mt-4">
      <%= f.submit "変更を保存", class: "btn btn-success px-4" %>
    </div>
  </div>
<% end %>

app/views/admin/customers/index.html.erb
<h3 class="title mb-4">会員一覧</h3>

<div class="table-container mb-4">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |c| %>
        <tr>
          <td><%= c.id %></td>
          <td><%= link_to c.last_name + " " + c.first_name, admin_customer_path(c), class: "text-decoration-none" %></td>
          <td><%= c.email %></td>
          <td><%= c.is_active ? "有効" : "退会" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/orders.html.erb
<h4 class="bg-light p-2 mb-4 pl-3" style="display: inline-block; margin-top: 20px;"><%= @customer.name + "さんの注文履歴" %></h4>
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.created_at.strftime("%Y/%m/%d %H:%M") %></td>
          <td><%= order.order_details.sum(:quantity) %></td>
          <td><%= link_to order.is_order_i18n, admin_order_path(order.id) %></td>  <!-- 修正: order.customer.id -> order.id -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- ページネーション -->
  <div class="d-flex justify-content-center mt-4">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h3 class="title mb-4"><%= @customer.last_name + " " + @customer.first_name + "さんの会員詳細" %></h3>

<div class="table-container mb-4">
  <table class="table table-striped table-bordered">
    <tbody>
      <tr>
        <td><strong>会員ID</strong></td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td><strong>氏名</strong></td>
        <td><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <td><strong>フリガナ</strong></td>
        <td><%= @customer.kana_last_name %> <%= @customer.kana_first_name %></td>
      </tr>
      <tr>
        <td><strong>郵便番号</strong></td>
        <td><%= @customer.post_code %></td>
      </tr>
      <tr>
        <td><strong>住所</strong></td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td><strong>電話番号</strong></td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td><strong>メールアドレス</strong></td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td><strong>会員ステータス</strong></td>
        <td><%= @customer.is_active ? "有効" : "退会" %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="d-flex justify-content-center">
  <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success btn-lg" %>
</div>